<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="assets/css/3rd/font-awesome.min.css"/>
    <link rel="stylesheet" href="assets/css/3rd/bootstrap.min.css">

    <script src="assets/js/3rd/jquery.min.js"></script>
    <script src="assets/js/3rd/popper.min.js"></script>
    <script src="assets/js/3rd/bootstrap.min.js"></script>
    <script src="assets/js/3rd/jquery.scrollUp.min.js"></script>
    <script src="assets/js/3rd/jssor.slider.min.js"></script>

    <link rel="stylesheet" href="assets/css/1.css"/>
    <script src="assets/js/1.js"></script>

    <title>Blog - Susu Family</title>
</head>

<body>
<!-- Header start -->
<header class="header-area">
    <!-- Top Header Start -->
    <div class="top-header">
        <div class="container">
            <div class="col-12">
                <div class="top-header-content d-flex">
                    <div class="search-form">
                        <form action="#" method="get">
                            <input type="search" name="search" class="form-control"
                                   placeholder="Search and hit enter...">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <div class="top-social-info">
                        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Top Header End -->

    <!-- Logo Area Start -->
    <div class="logo-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href="#">
                        <img src="assets/images/LogoSusuBlog_ByTailorBrands.jpg"/>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Logo Area End -->

    <!-- Navbar Area start -->
    <nav class="navbar navbar-expand-md navbar-light bg-light" id="navbar">
        <a class="navbar-brand menu-logo" href="#">
            <img src="assets/images/LogoSusuBlog_ByTailorBrands1.jpg" width="50" height="50" alt=""/>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-center main-menu" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Susu
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Link 1</a>
                        <a class="dropdown-item" href="#">Link 2</a>
                        <a class="dropdown-item" href="#">Link 3</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Food
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Link 1</a>
                        <a class="dropdown-item" href="#">Link 2</a>
                        <a class="dropdown-item" href="#">Link 3</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Travel
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Link 1</a>
                        <a class="dropdown-item" href="#">Link 2</a>
                        <a class="dropdown-item" href="#">Link 3</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Navbar Area End -->
</header>
<!-- Header End -->

<!-- Home page Area start -->
<section id="home-body" style="margin-top:10px;">
    <div class="containe-fluid">
        <div class="row">
            <!-- Jssor Slider Begin -->
            <div id="jssor_1"
                 style="position:relative;margin:0 auto;top:0px;left:0px;width:980px;height:350px;overflow:hidden;visibility:hidden;">
                <!-- Loading Screen -->
                <div data-u="loading" class="jssorl-009-spin"
                     style="position:absolute;top:0px;left:0px;width:980px;height:350px;text-align:center;background-color:rgba(0,0,0,0.7);">
                    <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;"
                         src="assets/images/gallery/slides/spin.svg"/>
                </div>
                <div data-u="slides"
                     style="cursor:default;position:relative;top:0px;left:0px;width:980px;height:350px;overflow:hidden;">
                    <div>
                        <a href="#1"><img data-u="image" src="assets/images/gallery/slides/001.jpg"/></a>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/005.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/006.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/007.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/008.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/009.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/010.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/011.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/024.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/025.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/026.jpg"/>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/slides/027.jpg"/>
                    </div>
                </div>
            </div>
            <!-- #endregion Jssor Slider End -->
            <!-- Jssor Slider End -->
        </div>
    </div>

</section>
<!-- Home page Area end -->
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aperiam asperiores corporis deleniti deserunt
    excepturi exercitationem, hic iure iusto labore libero magni non officia optio repellat repudiandae veritatis
    voluptates voluptatum!</p>
<!-- Footer area start -->
<section id="footer-area">
    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-12">
                <img src="assets/images/footer/foo-curve.png" alt="" style="vertical-align: middle; width: 100%;">
                <p class="footer-text">
                    Susu Family Blog
                </p>
            </div>
        </div>
    </div>
</section>
<!-- Footer area end -->
<a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647; display: none;"></a>
</body>
</html>