<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="assets/css/font-awesome.min.css" />
    <link rel="stylesheet" href="assets/css/1.css" />
    <script src="assets/js/1.js"></script>
    <script src="assets/js/jquery.scrollUp.min.js"></script>
    <script src="assets/js/jssor.slider.min.js"></script>

    <title>Blog - Susu Family</title>

    <script type="text/javascript">
        jQuery(document).ready(function ($) {

            var jssor_1_SlideshowTransitions = [
                {$Duration:1200,x:-0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
                {$Duration:1200,x:0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2}
            ];

            var jssor_1_options = {
                $AutoPlay: 1,
                $SlideshowOptions: {
                    $Class: $JssorSlideshowRunner$,
                    $Transitions: jssor_1_SlideshowTransitions,
                    $TransitionsOrder: 1
                },
                $ArrowNavigatorOptions: {
                    $Class: $JssorArrowNavigator$
                },
                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,
                    $Orientation: 2,
                    $NoDrag: true
                }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            /*#region responsive code begin*/

            var MAX_WIDTH = 980;

            function ScaleSlider() {
                var containerElement = jssor_1_slider.$Elmt.parentNode;
                var containerWidth = containerElement.clientWidth;

                if (containerWidth) {

                    var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

                    jssor_1_slider.$ScaleWidth(expectedWidth);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }

            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            /*#endregion responsive code end*/
        });
    </script>

    <style>
        /* jssor slider loading skin spin css */
        .jssorl-009-spin img {
            animation-name: jssorl-009-spin;
            animation-duration: 1.6s;
            animation-iteration-count: infinite;
            animation-timing-function: linear;
        }

        @keyframes jssorl-009-spin {
            from {
                transform: rotate(0deg);
            }

            to {
                transform: rotate(360deg);
            }
        }


        .jssora061 {display:block;position:absolute;cursor:pointer;}
        .jssora061 .a {fill:none;stroke:#fff;stroke-width:360;stroke-linecap:round;}
        .jssora061:hover {opacity:.8;}
        .jssora061.jssora061dn {opacity:.5;}
        .jssora061.jssora061ds {opacity:.3;pointer-events:none;}
    </style>


</head>

<body>
    <!-- Header start -->
    <header class="header-area">
        <!-- Top Header Start -->
        <div class="top-header">
            <div class="container">
                <div class="col-12">
                    <div class="top-header-content d-flex">
                        <div class="search-form">
                            <form action="#" method="get">
                                <input type="search" name="search" class="form-control"
                                    placeholder="Search and hit enter...">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        <div class="top-social-info">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Top Header End -->

        <!-- Logo Area Start -->
        <div class="logo-area text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <a href="#">
                            <img src="assets/images/LogoSusuBlog_ByTailorBrands.jpg" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Logo Area End -->

        <!-- Navbar Area start -->
        <nav class="navbar navbar-expand-md navbar-light bg-light" id="navbar">
            <a class="navbar-brand menu-logo" href="#">
                <img src="assets/images/LogoSusuBlog_ByTailorBrands1.jpg" width="50" height="50" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-flex justify-content-center main-menu" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Susu
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Food
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Travel
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Navbar Area End -->
    </header>
    <!-- Header End -->

    <!-- Home page Area start -->
    <section id="home-body">
        <div class="container" style="margin-top:10px;">
            <img src="assets/images/breadcrumb-line.png" alt="" style="vertical-align: middle; width: 100%">
            <!-- Jssor Slider Begin -->
            <div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:980px;height:380px;overflow:hidden;visibility:hidden;">
                <!-- Loading Screen -->
                <div data-u="loading" class="jssorl-009-spin" style="position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);">
                    <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;" src="../svg/loading/static-svg/spin.svg" />
                </div>
                <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:980px;height:380px;overflow:hidden;">
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/045.jpg" />
                        <div data-u="thumb">Slide Description 001</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/043.jpg" />
                        <div data-u="thumb">Slide Description 002</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/046.jpg" />
                        <div data-u="thumb">Slide Description 003</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/047.jpg" />
                        <div data-u="thumb">Slide Description 004</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/048.jpg" />
                        <div data-u="thumb">Slide Description 005</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/044.jpg" />
                        <div data-u="thumb">Slide Description 006</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/050.jpg" />
                        <div data-u="thumb">Slide Description 007</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/049.jpg" />
                        <div data-u="thumb">Slide Description 008</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/052.jpg" />
                        <div data-u="thumb">Slide Description 009</div>
                    </div>
                    <div>
                        <img data-u="image" src="assets/images/gallery/980x380/051.jpg" />
                        <div data-u="thumb">Slide Description 010</div>
                    </div>
                    <div style="background-color:#ff7c28;">
                        <div style="position:absolute;top:50px;left:50px;width:450px;height:62px;z-index:0;font-size:16px;color:#000000;line-height:24px;text-align:left;padding:5px;box-sizing:border-box;">Photos in this slider are to demostrate jssor slider,<br />
                            which are not licensed for any other purpose.
                        </div>
                        <div data-u="thumb">Terms of use photos in this slider</div>
                    </div>
                </div>
                <!-- Thumbnail Navigator -->
                <div data-u="thumbnavigator" style="position:absolute;bottom:0px;left:0px;width:980px;height:50px;color:#FFF;overflow:hidden;cursor:default;background-color:rgba(0,0,0,.5);">
                    <div data-u="slides">
                        <div data-u="prototype" style="position:absolute;top:0;left:0;width:980px;height:50px;">
                            <div data-u="thumbnailtemplate" style="position:absolute;top:0;left:0;width:100%;height:100%;font-family:verdana;font-weight:normal;line-height:50px;font-size:16px;padding-left:10px;box-sizing:border-box;"></div>
                        </div>
                    </div>
                </div>
                <!-- Arrow Navigator -->
                <div data-u="arrowleft" class="jssora061" style="width:55px;height:55px;top:0px;left:25px;" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
                    <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                        <path class="a" d="M11949,1919L5964.9,7771.7c-127.9,125.5-127.9,329.1,0,454.9L11949,14079"></path>
                    </svg>
                </div>
                <div data-u="arrowright" class="jssora061" style="width:55px;height:55px;top:0px;right:25px;" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
                    <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                        <path class="a" d="M5869,1919l5984.1,5852.7c127.9,125.5,127.9,329.1,0,454.9L5869,14079"></path>
                    </svg>
                </div>
            </div>
            <!-- #endregion Jssor Slider End -->

            <!-- Jssor Slider End -->
        </div>

    </section>
    <!-- Home page Area end -->

    <!-- Footer area start -->
    <section id="footer-area">
        <div class="container" style="margin-top:10px;">
            <div class="row">
                <div class="col-12">
                    <img src="assets/images/footer/foo-curve.png" alt="" style="vertical-align: middle; width: 100%;">
                    <p class="footer-text">
                        Susu Family Blog
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer area end -->
    <a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647; display: none;"></a>
</body>
</html>