<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="assets/css/font-awesome.min.css" />
    <link rel="stylesheet" href="assets/css/1.css" />
    <script src="assets/js/1.js"></script>
    <script src="assets/js/jquery.scrollUp.min.js"></script>

    <title>Blog - Susu Family</title>
</head>

<body>
    <!-- Header start -->
    <header class="header-area">
        <!-- Top Header Start -->
        <div class="top-header">
            <div class="container">
                <div class="col-12">
                    <div class="top-header-content d-flex">
                        <div class="search-form">
                            <form action="#" method="get">
                                <input type="search" name="search" class="form-control"
                                    placeholder="Search and hit enter...">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                        <div class="top-social-info">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Top Header End -->

        <!-- Logo Area Start -->
        <div class="logo-area text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <a href="#">
                            <img src="assets/images/LogoSusuBlog_ByTailorBrands.jpg" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Logo Area End -->

        <!-- Navbar Area start -->
        <nav class="navbar navbar-expand-md navbar-light bg-light" id="navbar">
            <a class="navbar-brand menu-logo" href="#">
                <img src="assets/images/LogoSusuBlog_ByTailorBrands1.jpg" width="50" height="50" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-flex justify-content-center main-menu" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Susu
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Food
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Travel
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Navbar Area End -->
    </header>
    <!-- Header End -->

    <!-- Home page Area start -->
    <!-- <section id="home_body">
        <div class="container" style="margin-top:10px;">
            <img src="assets/images/breadcrumb-line.png" alt="" style="vertical-align: middle;">
        </div>
        <div class="container" style="margin-top:10px;">
            <div id="demo" class="carousel slide" data-ride="carousel">
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                </ul>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="assets/images/1.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">\
                            <h3>May 4, 2019 / FOOD</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="assets/images/2.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">
                            <h3>Chicago</h3>
                            <p>Thank you, Chicago!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="assets/images/3.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">
                            <h3>New York</h3>
                            <p>We love the Big Apple!</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>
        <div class="container" style="margin-top:10px;">
            <img src="assets/images/breadcrumb-line.png" alt="" style="vertical-align: middle;">
        </div>
        <div class="container" style="margin-top:10px;">
            <div id="demo1" class="carousel slide" data-ride="carousel">
                <ul class="carousel-indicators">
                    <li data-target="#demo1" data-slide-to="0" class="active"></li>
                    <li data-target="#demo1" data-slide-to="1"></li>
                    <li data-target="#demo1" data-slide-to="2"></li>
                </ul>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="assets/images/11.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">\
                            <h3>May 4, 2019 / Travel</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="assets/images/22.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">
                            <h3>May 4, 2019 / Travel</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="assets/images/33.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">
                            <h3>New York</h3>
                            <p>We love the Big Apple!</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#demo1" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo1" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>
        <div class="container" style="margin-top:10px;">
            <img src="assets/images/breadcrumb-line.png" alt="" style="vertical-align: middle;">
        </div>
        <div class="container" style="margin-top:10px;">
            <div id="demo2" class="carousel slide" data-ride="carousel">
                <ul class="carousel-indicators">
                    <li data-target="#demo2" data-slide-to="0" class="active"></li>
                    <li data-target="#demo2" data-slide-to="1"></li>
                    <li data-target="#demo2" data-slide-to="2"></li>
                </ul>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="assets/images/1.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">\
                            <h3>May 4, 2019 / FOOD</h3>
                            <p>We had such a great time in LA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="assets/images/2.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">
                            <h3>Chicago</h3>
                            <p>Thank you, Chicago!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="assets/images/3.jpg" alt="Los Angeles" width="1100" height="500">
                        <div class="carousel-caption">
                            <h3>New York</h3>
                            <p>We love the Big Apple!</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#demo2" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo2" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>

    </section> -->
    <!-- Home page Area end -->

    <!-- footer area start -->
    <!-- <section id="footer">
        <div class="container" style="margin-top:10px;">
            <img src="assets/images/breadcrumb-line.png" alt="" style="vertical-align: middle;">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <p class="footer-text">
                        Susu Family Blog
                    </p>
                </div>
            </div>
        </div>

    </section> -->
    <!-- Footer area end -->

    <a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647; display: none;"></a>

</body>

</html>